# Site Settings
title: "TestedTruths: Insights from the QA Trenches"
email: paulmorrishhl@gmail.com
description: "Dive into the dynamic world of software testing with a blend of experienced insights, tool overviews, personal anecdotes, and step-by-step tutorials. Whether you're a seasoned QA professional or just starting out, discover the art and science of ensuring software excellence."
url: "https://paulmorrishhl.github.io"

# Build Settings
theme: minima

# Other Settings
author:
  name: Paul Morris
  email: paulmorrishhl@gmail.com

# Social Media Links (Optional)
twitter_username: paulmorrishhl
github_username:  paulmorrishhl
