# Site Settings
title: The Geordie Tester
email: paulmorrishhl@gmail.com
description: Everything related to software testing. Tutorials, news, opinion, rants, and more!
url: "https://paulmorrishhl.github.io"

theme: minima

# Other Settings
author:
  name: Paul Morris
  email: paulmorrishhl@gmail.com

# Social Media Links (Optional)
twitter_username: paulmorrishhl
github_username:  paulmorrishhl
