# Site Settings
title: The Geordie Tester
email: paulmorrishhl@gmail.com
description: Everything related to software testing. Tutorials, news, opinion, rants, and more!
url: "https://paulmorrishhl.github.io"

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

# Other Settings
author:
  name: Paul Morris
  email: paulmorrishhl@gmail.com

# Social Media Links (Optional)
twitter_username: paulmorrishhl
github_username:  paulmorrishhl
